#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/
#    healthcheck:
#      enabled: true
#    register-with-eureka: true #註冊到Eureka的註冊中心
#    fetch-registry:
#  instance:
#    statusPageUrlPath: ${server.servletPath}/info
#    healthCheckUrlPath: ${server.servletPath}/health

server:
  port: 8082
  servletPath: 127.0.0.1




eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
    instance:
      preferIpAddress: true
  instance:
    hostname: 127.0.0.1
    nonSecurePort: 80



spring:
  application:
    name: billshopmall
ribbon:
  eureka:
    enabled: true